coffeeshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import  views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cf'

urlpatterns= [
    path('', views.index, name='index'),
    path('menu/', views.Products, name='menu'),
    path('product/<slug>/', views.itemdetailView.as_view(), name='product'),
    path('add-cart/<slug>/',views.add_cart, name='add-cart'),
    path('remove-cart/<slug>/',views.remove_cart, name='remove-cart'),
    path('remove-single-item/<slug>/',views.remove_single_item, name='remove-single-item'),
    path('add-single-item/<slug>/',views.add_single_item, name='add-single-item'),
    path('cart/', views.cart.as_view(), name='cart'),
    path('accounts/', include('django.contrib.auth.urls')),
     
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings

# Create your models here.
class Category(models.Model):
    cate_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.cate_name


class Product(models.Model):
    cate = models.ForeignKey(Category, on_delete = models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    img = models.ImageField()
    slug = models.SlugField()

    def __str__(self):
        return self.name
    
    def get_url(self):
        return reverse("cf:product", kwargs={
            'slug' : self.slug
        })
    
    def get_add_cart_url(self):
        return reverse("cf:add-cart", kwargs={
            'slug' : self.slug
        })
    
    def get_remove_cart_url(self):
        return reverse("cf:remove-cart", kwargs={
            'slug' : self.slug
        })    


class OrderProduct(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} {self.product.name}"


    def get_total_product_price(self):
        return (self.quantity)*(self.product.price)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    products = models.ManyToManyField(OrderProduct)
    start_date = models.DateTimeField(auto_now_add = True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return (self.user.username)

    def total_price(self):
        total = 0
        for item in self.products.all():
            total = total + item.get_total_product_price()
        return total

home/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Product, Order, OrderProduct
from django.views.generic import DetailView, ListView, TemplateView, View
from django.utils import timezone
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def index(request):
    listCate = Category.objects.all()
    listPro = Product.objects.all()
    return render(request, 'home/index.html',{'Categories':listCate, 'Products':listPro,'nav': 'home'} )


def Products(request):
    listCate = Category.objects.all()
    listPro = Product.objects.all()
    return render(request, 'home/menu.html', {'Categories':listCate, 'Products':listPro,'nav': 'menu'})


class itemdetailView(DetailView):
    model = Product
    template_name = "home/product.html"


@login_required()
def add_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_product , created = OrderProduct.objects.get_or_create(
        product = product,
        user = request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user = request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__slug = product.slug).exists():
            order_product.quantity += 1
            order_product.save()
            messages.info(request, "sản phẩm đã được cập nhật số lượng")
        else:
            messages.info(request, "sản phẩm này đã được thêm vào giỏ hàng ")
            order.products.add(order_product)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user = request.user, ordered_date=ordered_date)
        order.products.add(order_product)
        messages.info(request, "sản phẩm này đã được thêm vào giỏ hàng ")
    return redirect("cf:product", slug=slug)


@login_required()
def remove_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user = request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__slug = product.slug).exists():
            order_product = OrderProduct.objects.filter(
                product = product,
                user = request.user,
                ordered=False
            )[0]
            order.products.remove(order_product)
            messages.info(request, "sản phẩm này đã xóa khỏi giỏ hàng")
            return redirect("cf:cart")
        else:
            messages.info(request, "sản phẩm này đã chưa có trong giỏ hàng")
            return redirect("cf:cart")       
    else:
        messages.info(request, "bạn chưa đặt hàng")
        return redirect("cf:cart")


@login_required()
def remove_single_item(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user = request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__slug = product.slug).exists():
            order_product = OrderProduct.objects.filter(
                product = product,
                user = request.user,
                ordered=False
            )[0]
            if order_product.quantity >1:
                order_product.quantity -= 1
                order_product.save()
            else: 
                order.products.remove(order_product)
            
            messages.info(request, "sản phẩm này đã xóa khỏi giỏ hàng")
            return redirect("cf:cart")
        else:
            messages.info(request, "sản phẩm này đã chưa có trong giỏ hàng")
            return redirect("cf:cart")       
    else:
        messages.info(request, "bạn chưa đặt hàng")
        return redirect("cf:cart")


@login_required()
def add_single_item(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_product , created = OrderProduct.objects.get_or_create(
        product = product,
        user = request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user = request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__slug = product.slug).exists():
            order_product.quantity += 1
            order_product.save()
            messages.info(request, "sản phẩm đã được cập nhật số lượng")
        else:
            messages.info(request, "sản phẩm này đã được thêm vào giỏ hàng ")
            order.products.add(order_product)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user = request.user, ordered_date=ordered_date)
        order.products.add(order_product)
        messages.info(request, "sản phẩm này đã được thêm vào giỏ hàng ")
    return redirect("cf:cart")


# def login(request):
#     return render(request, 'home/login.html')


#class cart(LoginRequiredMixin, TemplateView):
#    template_name = 'home/cart.html'



class cart(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user =self.request.user, ordered = False)
            context = {
                'order' : order
            }
            return render(self.request, 'home/cart.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "ban can kich hoat dat hang")
            return redirect("/")

        

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
{% load cart_templatetags %}
<html lang="en">
<head>
    <title>MY COFFEE SHOP D.V.AN</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=devic e-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
                <div class="container">
                  <a class="navbar-brand" href="{% url 'cf:index' %}">Coffee<small>Blend</small></a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                  </button>
                  <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav ml-auto">
                      <li class="nav-item {% if nav == 'home' %} active {% endif %}" ><a href="{% url 'cf:index' %}" class="nav-link">Trang Chủ</a></li>
                      <li class="nav-item {% if nav == 'menu' %} active {% endif %}"><a href="{% url 'cf:menu' %}" class="nav-link">Thực Đơn</a></li>
                      <li class="nav-item"><a href="services.html" class="nav-link">Services</a></li>
                      <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
                      <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
                      <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="room.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
                      <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="shop.html">Shop</a>
                        <a class="dropdown-item" href="product-single.html">Single Product</a>
                        <a class="dropdown-item" href="room.html">Cart</a>
                        <a class="dropdown-item" href="checkout.html">Checkout</a>
                      </div>
                    </li>
                      <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                      
                    </ul>
                    <ul class="navbar-nav"> 
                    {% if request.user.is_authenticated %}                    
                    <li class="nav-item cart"><a href="{% url 'cf:cart' %}" class="nav-link"><span class="icon icon-shopping_cart"></span><span class="bag d-flex justify-content-center align-items-center"><small></small>{{request.user|cart_item_count}}</small></span></a></li>
                    <li class="nav-item " ><a href="{% url 'cf:logout' %}" class="nav-link">Logout</a></li>
                    {% else %}
                    <li class="nav-item cart"><a href="{% url 'cf:cart' %}" class="nav-link"><span class="icon icon-shopping_cart"></span><span class="bag d-flex justify-content-center align-items-center"><small></small>0</small></span></a></li>
                    <li class="nav-item " ><a href="{% url 'cf:login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item " ><a href="." class="nav-link">Signup</a></li>
                    {% endif %}
                  </div>
                  </div>
    </nav>


    {% block content %}

    
    {% endblock %}


    <footer class="ftco-footer ftco-section img">
            <div class="overlay"></div>
          <div class="container">
            <div class="row mb-5">
              <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                  <h2 class="ftco-heading-2">About Us</h2>
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                  <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                    <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                    <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                    <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                  <h2 class="ftco-heading-2">Recent Blog</h2>
                  <div class="block-21 mb-4 d-flex">
                    <a class="blog-img mr-4" style="background-image: url(static/images/image_1.jpg);"></a>
                    <div class="text">
                      <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                      <div class="meta">
                        <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                        <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                        <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                      </div>
                    </div>
                  </div>
                  <div class="block-21 mb-4 d-flex">
                    <a class="blog-img mr-4" style="background-image: url(static/images/image_2.jpg);"></a>
                    <div class="text">
                      <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                      <div class="meta">
                        <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                        <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                        <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
                 <div class="ftco-footer-widget mb-4 ml-md-4">
                  <h2 class="ftco-heading-2">Services</h2>
                  <ul class="list-unstyled">
                    <li><a href="#" class="py-2 d-block">Cooked</a></li>
                    <li><a href="#" class="py-2 d-block">Deliver</a></li>
                    <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
                    <li><a href="#" class="py-2 d-block">Mixed</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                      <ul>
                        <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                        <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                        <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                      </ul>
                    </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 text-center">
    
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="{% static 'https://colorlib.com' %}" target="_blank">Colorlib</a>
      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
              </div>
            </div>
          </div>
    </footer>

    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

home/templates/home/cart.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<body>
	<section class="home-slider owl-carousel">

		<div class="slider-item" style="background-image: url(images/bg_3.jpg);" data-stellar-background-ratio="0.5">
			<div class="overlay"></div>
			<div class="container">
				<div class="row slider-text justify-content-center align-items-center">

					<div class="col-md-7 col-sm-12 text-center ftco-animate">
						<h1 class="mb-3 mt-5 bread">Cart</h1>
						<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'cf:index' %}">Trang Chủ</a></span> <span>Cart</span>
						</p>
					</div>

				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section ftco-cart">
		<div class="container">
			<h1>Order Summary</h1>
			<div class="row">
				<div class="col-md-12 ftco-animate">
					<div class="cart-list">
						<table class="table">
							<thead class="thead-primary">
								<tr class="text-center">
									<th>&nbsp;</th>
									<th>Images</th>
									<th>Product</th>
									<th>Price</th>
									<th>Quantity</th>
									<th>Total</th>
								</tr>
							</thead>
							<tbody>
								{% for item in order.products.all %}
								<tr class="text-center">
									<td class="product-remove"><a href="{% url 'cf:remove-cart' item.product.slug %}"><span class="icon-close"></span></a></td>
									<td class="image-prod">
										<div class="img" style="background-image: url('{{ item.product.img.url }}');"></div>
									</td>
									<td class="product-name">
										<h3>{{item.product.name}}</h3>
										<p>Far far away</p>
									</td>
									<td class="price">{{item.product.price}}</td>									
									<td class="quantity">
										<a href="{% url 'cf:remove-single-item' item.product.slug %}"><i class="far fa-minus mr-1"></i> - </a>
										{{item.quantity}}
										<a href="{% url 'cf:add-single-item' item.product.slug %}"><i class="far fa-plus ml-1"></i> + </a>
									</td>
									<td class="total">{{item.get_total_product_price}}</td>
									{% empty  %}
									<tr class="text-center">
										<td colspan='6'>Your Cart Is Empty </td>
									</tr>
								</tr><!-- END TR-->
								{% endfor %}



							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="row justify-content-end">
				<div class="col col-lg-3 col-md-6 mt-5 cart-wrap ftco-animate">
					<div class="cart-total mb-3">
						<h3>Cart Totals</h3>
						<p class="d-flex">
							<span>Subtotal</span>
							<span>{{ order.total_price }}</span>
						</p>
						<p class="d-flex">
							<span>Discount</span>
							<span>0</span>
						</p>
						<hr>
						<p class="d-flex total-price">
							<span>Total</span>
							<span>{{ order.total_price }}</span>
						</p>
					</div>
					<p class="text-center"><a href="checkout.html" class="btn btn-primary py-3 px-4">Proceed to
							Checkout</a></p>
					<p class="text-center"><a href="{% url 'cf:menu' %}" class="btn btn-info py-3 px-4 float-center">Continue Shopping</a></p>
				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center mb-5 pb-3">
				<div class="col-md-7 heading-section ftco-animate text-center">
					<span class="subheading">Discover</span>
					<h2 class="mb-4">Related products</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
						live the blind texts.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					<div class="menu-entry">
						<a href="#" class="img" style="background-image: url(images/menu-1.jpg);"></a>
						<div class="text text-center pt-4">
							<h3><a href="#">Coffee Capuccino</a></h3>
							<p>A small river named Duden flows by their place and supplies</p>
							<p class="price"><span>$5.90</span></p>
							<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="menu-entry">
						<a href="#" class="img" style="background-image: url(images/menu-2.jpg);"></a>
						<div class="text text-center pt-4">
							<h3><a href="#">Coffee Capuccino</a></h3>
							<p>A small river named Duden flows by their place and supplies</p>
							<p class="price"><span>$5.90</span></p>
							<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="menu-entry">
						<a href="#" class="img" style="background-image: url(images/menu-3.jpg);"></a>
						<div class="text text-center pt-4">
							<h3><a href="#">Coffee Capuccino</a></h3>
							<p>A small river named Duden flows by their place and supplies</p>
							<p class="price"><span>$5.90</span></p>
							<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="menu-entry">
						<a href="#" class="img" style="background-image: url(images/menu-4.jpg);"></a>
						<div class="text text-center pt-4">
							<h3><a href="#">Coffee Capuccino</a></h3>
							<p>A small river named Duden flows by their place and supplies</p>
							<p class="price"><span>$5.90</span></p>
							<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

</body>
{% endblock %}